environment: dev

dockerConfigJson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICAgICAgICJyZWdpc3RyeS5tYXJpYW5jaGVsbXVzLnJvIjogew0KICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJhemh6T210dGVXcHFaMjF0ZVdGblpYRmxkV0k9Ig0KICAgICAgICAgICAgfQ0KICAgIH0NCn0=

serviceMonitor:
  name: service-monitor

probes:
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

secret:
  name: super-secret
  key: password

envVariables:
  - name: REDIS_HOST
    value: "{{ include \"generic-app.fullname\" . }}-redis"
  - name: BACKEND_PORT
    value: "{{ .Values.appService.port }}"
  - name: SECRET_DECODED
    valueFrom: "secretKeyRef"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"

appService:
  enabled: true
  name: app
  port: 5000
  targetPort: 5000
  nodePort: 32701
  type: NodePort
  protocol: TCP
  loadBalancerIP: 192.168.49.102

appDeployment:
  enabled: true
  name: app
  replicaCount: 1
  image:
    repository: registry.marianchelmus.ro
    name: generic-app-service
    tag: latest
  containerPort: 5000
  secretEnvName: env-secrets

redisDeployment:
  enabled: true
  name: redis
  replicaCount: 1
  image:
    repository: redis
    tag: latest
  containerPort: 6379
  volumeMount:
    name: redis-config-volume
    mountPath: /usr/local/etc/redis/redis.conf
    subPath: redis.conf
    readOnly: true
  configMap:
    enabled: true
    name: redis-config

redisService:
  enabled: true
  name: redis

imagePullSecret: regcred
