environment: dev

dockerConfigJson: base64encoded-value-of-$(cat ~/.docker/config.json)

probes:
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

secret:
  name: super-secret
  key: password

envVariables:
  - name: REDIS_HOST
    value: "{{ include \"hello-world.fullname\" . }}-redis"
  - name: BACKEND_PORT
    value: "{{ .Values.backendService.port }}"
  - name: SECRET_DECODED
    valueFrom: "secretKeyRef"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"

backendService:
  enabled: true
  name: backend
  port: 5000
  targetPort: 5000
  nodePort: 32701
  type: NodePort
  protocol: TCP

backendDeployment:
  enabled: true
  name: backend
  replicaCount: 1
  image:
    repository: registry.marianchelmus.ro
    name: hello-world-service
    tag: latest
  containerPort: 5000

redisDeployment:
  enabled: true
  name: redis
  replicaCount: 1
  image:
    repository: redis
    tag: latest
  containerPort: 6379
  volumeMount:
    name: redis-config-volume
    mountPath: /usr/local/etc/redis/redis.conf
    subPath: redis.conf
    readOnly: true
  configMap:
    enabled: true
    name: redis-config

redisService:
  enabled: true
  name: redis

imagePullSecret: regcred
