apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world-nginx.fullname" . }}-backend
  labels:
    {{- include "hello-world-nginx.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: registry.marianchelmus.ro/hello-world-service:latest
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: {{ include "hello-world-nginx.fullname" . }}-redis
      imagePullSecrets:
      - name: regcred