apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world-nginx.fullname" . }}-backend
  labels:
    {{- include "hello-world-nginx.labels" . | nindent 4 }}
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backendService.port }}
      targetPort: {{ .Values.backendService.targetPort }}
  type: LoadBalancer  # Use ClusterIP or NodePort if you don’t need external access
