{{- if .Values.appDeployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-app.fullname" . }}-app
  labels:
    app.kubernetes.io/name: {{ include "generic-app.name" . }}
    app.kubernetes.io/component: {{ .Values.appDeployment.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.appDeployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "generic-app.name" . }}
      app.kubernetes.io/component: {{ .Values.appDeployment.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "generic-app.name" . }}
        app.kubernetes.io/component: {{ .Values.appDeployment.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/version: {{ .Chart.Version | quote }}
    spec:
      containers:
      - name: {{ .Values.appDeployment.name }}
        image: "{{ .Values.appDeployment.image.repository }}/{{ .Values.appDeployment.image.name }}:{{ .Values.appDeployment.image.tag }}"
        ports:
        - containerPort: {{ .Values.appDeployment.containerPort }}
        env:
          {{- range .Values.envVariables }}
          {{- if eq .valueFrom "secretKeyRef" }}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.secret.name }}
                key: {{ $.Values.secret.key }}
          {{- else }}
          - name: {{ .name }}
            value: {{ tpl .value $ | quote }}
          {{- end }}
          {{- end }}
        envFrom:
          - secretRef:
              name: {{ .Values.appDeployment.secretEnvName }}
        resources:
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
        livenessProbe:
          tcpSocket:
            port: {{ .Values.appDeployment.containerPort }}
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds | default 30 }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds | default 10 }}
          timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds | default 5 }}
          failureThreshold: {{ .Values.probes.liveness.failureThreshold | default 3 }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.appDeployment.containerPort }}
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds | default 30 }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds | default 10 }}
          timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds | default 5 }}
          failureThreshold: {{ .Values.probes.readiness.failureThreshold | default 3 }}
      imagePullSecrets:
      - name: {{ include "generic-app.fullname" . }}-{{ .Values.imagePullSecret }}
{{- end }}
