apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-app.fullname" . }}-{{ .Values.imagePullSecret }}
  labels:
    app.kubernetes.io/component: image-pull-secret
    {{- include "generic-app.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfigJson | quote }}
