apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world-nginx.fullname" . }}
  labels:
    {{- include "hello-world-nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontendService.type }}
  ports:
    - port: {{ .Values.frontendService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello-world-nginx.selectorLabels" . | nindent 4 }}
