apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world-nginx.fullname" . }}-redis
  labels:
    {{- include "hello-world-nginx.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
