apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world-nginx.fullname" . }}-redis
  labels:
    {{- include "hello-world-nginx.labels" . | nindent 4 }}
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP  # This makes it accessible only within the cluster
