{{- if .Values.redisDeployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-app.fullname" . }}-{{ .Values.redisDeployment.name }}
  labels:
    app.kubernetes.io/component: redis
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redisDeployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "generic-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "generic-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redisDeployment.image.repository }}:{{ .Values.redisDeployment.image.tag }}"
          ports:
            - containerPort: {{ .Values.redisDeployment.containerPort }}
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
          {{- if .Values.redisDeployment.configMap.enabled }}
          command: [ "redis-server", "{{ .Values.redisDeployment.volumeMount.mountPath }}" ]
          volumeMounts:
            - name: {{ .Values.redisDeployment.volumeMount.name }}
              mountPath: {{ .Values.redisDeployment.volumeMount.mountPath }}
              subPath: {{ .Values.redisDeployment.volumeMount.subPath }}
              readOnly: {{ .Values.redisDeployment.volumeMount.readOnly }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.redisDeployment.containerPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold | default 3 }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.redisDeployment.containerPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold | default 3 }}
      {{- if .Values.redisDeployment.configMap.enabled }}
      volumes:
        - name: {{ .Values.redisDeployment.volumeMount.name }}
          configMap:
            name: {{ include "generic-app.fullname" . }}-{{ .Values.redisDeployment.configMap.name }}
      {{- end }}
{{- end }}
