{{- if .Values.redisService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-app.fullname" . }}-{{ .Values.redisService.name }}
  labels:
    app.kubernetes.io/component: redis
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
{{- end }}
