{{- if .Values.redisService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world-nginx.fullname" . }}-{{ .Values.redisService.name }}
  labels:
    {{- include "hello-world-nginx.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.redisService.name }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
{{- end }}