apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app.kubernetes.io/component: credentials
    {{- include "generic-app.labels" . | nindent 4 }}
type: Opaque
data:
  password: MTIzNDU2
