apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: {{ include "generic-app.fullname" . }}-{{ .Values.serviceMonitor.name }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: 10s
      port: {{ .Values.appService.portName | quote }}
      scheme: {{ .Values.appService.portScheme }}
      path: {{ .Values.appService.metricsPath }}
  selector:
    matchLabels:
      {{- include "generic-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.appService.name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}

