apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring  # Namespace where Prometheus is looking for ServiceMonitors
  name: {{ include "generic-app.fullname" . }}-{{ .Values.serviceMonitor.name }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: 30s
      port: {{ .Values.appService.port | quote }}  # Ensure this matches the Service port
      path: /metrics  # Assuming Prometheus metrics are exposed on /metrics
  selector:
    matchLabels:
      {{- include "generic-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}  # Namespace where your application is deployed
