apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: {{ include "generic-app.fullname" . }}-{{ .Values.serviceMonitor.name }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: 30s
      port: {{ .Values.appService.port | quote }}  # Ensure this matches the Service port
      path: /metrics  # Assuming Prometheus metrics are exposed on /metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "generic-app.name" . }}
      app.kubernetes.io/component: {{ .Values.appService.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/part-of: {{ .Chart.Name }}
      app.kubernetes.io/version: {{ .Chart.Version | quote }}
  namespaceSelector:
    any: true
