{{- if .Values.backendService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: {{ .Values.backendService.name }}
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.backendService.name }}
  ports:
    - protocol: {{ .Values.backendService.protocol }}
      port: {{ .Values.backendService.port }}
      targetPort: {{ .Values.backendService.targetPort }}
      nodePort: {{ .Values.backendService.nodePort }}
  type: {{ .Values.backendService.type }}
{{- end }}
