{{- if .Values.appService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-app.fullname" . }}-{{ .Values.appService.name }}
  labels:
    app.kubernetes.io/name: {{ include "generic-app.name" . }}
    app.kubernetes.io/component: {{ .Values.appService.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    {{- include "generic-app.labels" . | nindent 4 }}
  {{- if and (eq .Values.appService.type "LoadBalancer") .Values.appService.loadBalancerIP }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.appService.loadBalancerIP }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "generic-app.name" . }}
    app.kubernetes.io/component: {{ .Values.appService.name }}
  ports:
    - protocol: {{ .Values.appService.protocol }}
      port: {{ .Values.appService.port }}
      targetPort: {{ .Values.appService.targetPort }}
      {{- if .Values.appService.nodePort }}
      nodePort: {{ .Values.appService.nodePort }}
      {{- end }}
  type: {{ .Values.appService.type }}
{{- end }}
